var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/users/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lot_b7._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10x__yf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(admin)_layout_tsx_0l9ec0o._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(admin)_users_page_actions_0hyrvtp.js")
R.m(4084)
module.exports=R.m(4084).exports
