import { Repository } from 'typeorm';
import { UsersService } from './users.service';
import { Job } from '../jobs/job.entity';
import { Review } from '../reviews/review.entity';
import { Offer } from '../jobs/offer.entity';
import type { AuthenticatedRequest } from '../../common/types/auth.types';
export declare class UsersController {
    private readonly svc;
    private jobsRepo;
    private reviewsRepo;
    private offersRepo;
    constructor(svc: UsersService, jobsRepo: Repository<Job>, reviewsRepo: Repository<Review>, offersRepo: Repository<Offer>);
    getMe(req: AuthenticatedRequest): Promise<{
        id: string;
        fullName: string;
        phoneNumber: string;
        email: string;
        profileImageUrl: string;
        identityPhotoUrl: string;
        documentPhotoUrl: string;
        identityVerified: boolean;
        birthDate: string;
        gender: string;
        city: string;
        district: string;
        address: string;
        isPhoneVerified: boolean;
        role: import("./user.entity").UserRole;
        tokenBalance: number;
        asCustomerTotal: number;
        asCustomerSuccess: number;
        asCustomerFail: number;
        asWorkerTotal: number;
        asWorkerSuccess: number;
        asWorkerFail: number;
        averageRating: number;
        totalReviews: number;
        reputationScore: number;
        workerCategories: string[] | null;
        workerBio: string | null;
        hourlyRateMin: number | null;
        hourlyRateMax: number | null;
        serviceRadiusKm: number;
        isAvailable: boolean;
        latitude: number | null;
        longitude: number | null;
        lastLocationAt: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    updateLocation(req: AuthenticatedRequest, body: {
        latitude: number;
        longitude: number;
    }): Promise<{
        ok: boolean;
    }>;
    updateMe(req: AuthenticatedRequest, body: {
        fullName?: string;
        email?: string;
        phoneNumber?: string;
        birthDate?: string;
        gender?: string;
        city?: string;
        district?: string;
        address?: string;
        identityPhotoUrl?: string;
        documentPhotoUrl?: string;
    }): Promise<{
        id: string;
        fullName: string;
        phoneNumber: string;
        email: string;
        profileImageUrl: string;
        identityPhotoUrl: string;
        documentPhotoUrl: string;
        identityVerified: boolean;
        birthDate: string;
        gender: string;
        city: string;
        district: string;
        address: string;
        isPhoneVerified: boolean;
        role: import("./user.entity").UserRole;
        tokenBalance: number;
        asCustomerTotal: number;
        asCustomerSuccess: number;
        asCustomerFail: number;
        asWorkerTotal: number;
        asWorkerSuccess: number;
        asWorkerFail: number;
        averageRating: number;
        totalReviews: number;
        reputationScore: number;
        workerCategories: string[] | null;
        workerBio: string | null;
        hourlyRateMin: number | null;
        hourlyRateMax: number | null;
        serviceRadiusKm: number;
        isAvailable: boolean;
        latitude: number | null;
        longitude: number | null;
        lastLocationAt: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    getWorkers(category?: string, city?: string): Promise<{
        id: string;
        fullName: string;
        phoneNumber: string;
        email: string;
        profileImageUrl: string;
        identityPhotoUrl: string;
        documentPhotoUrl: string;
        identityVerified: boolean;
        birthDate: string;
        gender: string;
        city: string;
        district: string;
        address: string;
        isPhoneVerified: boolean;
        role: import("./user.entity").UserRole;
        tokenBalance: number;
        asCustomerTotal: number;
        asCustomerSuccess: number;
        asCustomerFail: number;
        asWorkerTotal: number;
        asWorkerSuccess: number;
        asWorkerFail: number;
        averageRating: number;
        totalReviews: number;
        reputationScore: number;
        workerCategories: string[] | null;
        workerBio: string | null;
        hourlyRateMin: number | null;
        hourlyRateMax: number | null;
        serviceRadiusKm: number;
        isAvailable: boolean;
        latitude: number | null;
        longitude: number | null;
        lastLocationAt: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    getPublicProfile(id: string): Promise<{
        averageRating: number;
        totalReviews: number;
        reputationScore: number;
        reviews: {
            id: string;
            rating: number;
            comment: string;
            createdAt: Date;
            reviewer: {
                id: string;
                fullName: string;
                profileImageUrl: string;
            };
        }[];
        pastPhotos: string[];
        id: string;
        fullName: string;
        phoneNumber: string;
        email: string;
        profileImageUrl: string;
        identityPhotoUrl: string;
        documentPhotoUrl: string;
        identityVerified: boolean;
        birthDate: string;
        gender: string;
        city: string;
        district: string;
        address: string;
        isPhoneVerified: boolean;
        role: import("./user.entity").UserRole;
        tokenBalance: number;
        asCustomerTotal: number;
        asCustomerSuccess: number;
        asCustomerFail: number;
        asWorkerTotal: number;
        asWorkerSuccess: number;
        asWorkerFail: number;
        workerCategories: string[] | null;
        workerBio: string | null;
        hourlyRateMin: number | null;
        hourlyRateMax: number | null;
        serviceRadiusKm: number;
        isAvailable: boolean;
        latitude: number | null;
        longitude: number | null;
        lastLocationAt: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
}
