-- Phase 174: Float → Integer minor units (kuruş) shadow column migration
ALTER TABLE users ADD COLUMN IF NOT EXISTS tokenBalanceMinor BIGINT DEFAULT 10000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hourlyRateMinMinor BIGINT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hourlyRateMaxMinor BIGINT NULL;
UPDATE users SET tokenBalanceMinor = ROUND(tokenBalance * 100) WHERE tokenBalance IS NOT NULL;
UPDATE users SET hourlyRateMinMinor = ROUND(hourlyRateMin * 100) WHERE hourlyRateMin IS NOT NULL;
UPDATE users SET hourlyRateMaxMinor = ROUND(hourlyRateMax * 100) WHERE hourlyRateMax IS NOT NULL;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS priceMinor BIGINT NOT NULL DEFAULT 0;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS counterPriceMinor BIGINT NULL;
UPDATE offers SET priceMinor = ROUND(price * 100);
UPDATE offers SET counterPriceMinor = ROUND(counterPrice * 100) WHERE counterPrice IS NOT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS budgetMinMinor BIGINT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS budgetMaxMinor BIGINT NULL;
UPDATE jobs SET budgetMinMinor = ROUND(budgetMin * 100) WHERE budgetMin IS NOT NULL;
UPDATE jobs SET budgetMaxMinor = ROUND(budgetMax * 100) WHERE budgetMax IS NOT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS agreedPriceMinor BIGINT NULL;
UPDATE bookings SET agreedPriceMinor = ROUND(agreedPrice * 100) WHERE agreedPrice IS NOT NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS priceMinor BIGINT NULL;
UPDATE service_requests SET priceMinor = ROUND(price * 100) WHERE price IS NOT NULL;
ALTER TABLE service_request_applications ADD COLUMN IF NOT EXISTS priceMinor BIGINT NULL;
UPDATE service_request_applications SET priceMinor = ROUND(price * 100) WHERE price IS NOT NULL;
ALTER TABLE payment_escrows ADD COLUMN IF NOT EXISTS amountMinor BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payment_escrows ADD COLUMN IF NOT EXISTS platformFeeMinor BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payment_escrows ADD COLUMN IF NOT EXISTS workerPayoutMinor BIGINT NOT NULL DEFAULT 0;
UPDATE payment_escrows SET amountMinor = ROUND(amount * 100), platformFeeMinor = ROUND(platformFee * 100), workerPayoutMinor = ROUND(workerPayout * 100);
ALTER TABLE token_transactions ADD COLUMN IF NOT EXISTS amountMinor BIGINT NOT NULL DEFAULT 0;
UPDATE token_transactions SET amountMinor = ROUND(amount * 100);
CREATE INDEX IF NOT EXISTS idx_escrow_status_amount ON payment_escrows(status, amountMinor);
CREATE INDEX IF NOT EXISTS idx_users_token_minor ON users(tokenBalanceMinor);
