var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/onboarding-mgmt/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tk.xg5._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0y0jsct.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(admin)_layout_tsx_0l9ec0o._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(admin)_onboarding-mgmt_page_actions_0bcc.1z.js")
R.m(49057)
module.exports=R.m(49057).exports
