var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/workforce/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04...-j._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0quet0c.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y~gs73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v73tbn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(admin)_layout_tsx_0l9ec0o._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(admin)_workforce_page_actions_0-2ujgm.js")
R.m(63852)
module.exports=R.m(63852).exports
